### PR TITLE
Allow access to private E2E WC using kubeconfig generated by Teleport

### PR DESCRIPTION
**Pull request by anvddriesch**
Towards https://github.com/giantswarm/giantswarm/issues/30767

### CODE REVIEW

**Review by AverageMarcus — CHANGES_REQUESTED** [review]
Please make sure to update the docs too: https://github.com/giantswarm/clustertest#supported-environment-variables

Are you aware that this change isn't enough to solve https://github.com/giantswarm/giantswarm/issues/30767 ? 

We only use the CAPI kubeconfig until we can reach the WC API server and then we immediately create a new ServiceAccount to make use of and generate a kubeconfig for that.

**Comment by tuladhar** [comment]
> Please make sure to update the docs too: https://github.com/giantswarm/clustertest#supported-environment-variables
> 
> Are you aware that this change isn't enough to solve [giantswarm/giantswarm#30767](https://github.com/giantswarm/giantswarm/issues/30767) ?
> 
> We only use the CAPI kubeconfig until we can reach the WC API server and then we immediately create a new ServiceAccount to make use of and generate a kubeconfig for that.

I’ve already discussed with Marcus about the need to carry out some additional integration and refactoring work. We’ll go over the details in our upcoming call on Monday.

**Review by AverageMarcus — APPROVED** [review]

**Comment by AverageMarcus** [comment]
Updated to automatically use Teleport kubeconfig if detected and if not fallback to existing logic. Tested with both paths.

**Comment by tuladhar** [comment]
> Updated to automatically use Teleport kubeconfig if detected and if not fallback to existing logic. Tested with both paths.

Same here - Tested and everything looks good.

**Pull request merged**
